# 使用语言
language: node_js
node_js: 10

branches:
  only:
    - src

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_install:
  - git config --global user.name "loatheb"
  - git config --global user.email "loatheb.zhao@gmail.com"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli

install:
  - yarn

script:
  - hexo clean
  - hexo g

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "[Travis-CI] Auto Build HEXO Blog"
  - git push --quiet --force https://$GITHUB_AUTO_BUILD_TOKEN@github.com/loatheb/loatheb.github.io.git master