menu:
    博客: /
    归档: /archives/
    微博: https://weibo.com/loatheb
    GitHub: https://github.com/loatheb
    Rss 订阅: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: loatheb
duoshuo:

# Analytics
# google-analytics:
ga: UA-113346354-1
ba: b0c67e473d188544afaabed16e997cf5

# Copyright Infomation
startyear: 2017
