menu:
    Blog: /
    Archive: /archives/
    Weibo: https://weibo.com/loatheb
    GitHub: https://github.com/loatheb
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: loatheb
duoshuo:

# Analytics
# google-analytics:
ga: UA-113346354-1

# Copyright Infomation
startyear: 2016
